<template>
  <div>
    <scroll class="content">
      <ul>
        <li>个人信心1</li>
        <li>个人信心2</li>
        <li>个人信心3</li>
        <li>个人信心4</li>
        <li>个人信心5</li>
        <li>个人信心6</li>
        <li>个人信心7</li>
        <li>个人信心8</li>
        <li>个人信心9</li>
        <li>个人信心10</li>
        <li>个人信心11</li>
        <li>个人信心12</li>
        <li>个人信心13</li>
        <li>个人信心14</li>
        <li>个人信心15</li>
        <li>个人信心16</li>
        <li>个人信心17</li>
        <li>个人信心18</li>
        <li>个人信心19</li>
        <li>个人信心20</li>
        <li>个人信心21</li>
        <li>个人信心22</li>
        <li>个人信心23</li>
        <li>个人信心24</li>
        <li>个人信心25</li>
        <li>个人信心26</li>
        <li>个人信心27</li>
        <li>个人信心28</li>
        <li>个人信心29</li>
        <li>个人信心30</li>
        <li>个人信心31</li>
        <li>个人信心32</li>
        <li>个人信心33</li>
        <li>个人信心34</li>
        <li>个人信心35</li>
        <li>个人信心36</li>
        <li>个人信心37</li>
        <li>个人信心38</li>
        <li>个人信心39</li>
        <li>个人信心40</li>
        <li>个人信心41</li>
        <li>个人信心42</li>
        <li>个人信心43</li>
        <li>个人信心44</li>
        <li>个人信心45</li>
        <li>个人信心46</li>
        <li>个人信心47</li>
        <li>个人信心48</li>
        <li>个人信心49</li>
        <li>个人信心50</li>
        <li>个人信心51</li>
        <li>个人信心52</li>
        <li>个人信心53</li>
        <li>个人信心54</li>
        <li>个人信心55</li>
        <li>个人信心56</li>
        <li>个人信心57</li>
        <li>个人信心58</li>
        <li>个人信心59</li>
        <li>个人信心60</li>
        <li>个人信心61</li>
        <li>个人信心62</li>
        <li>个人信心63</li>
        <li>个人信心64</li>
        <li>个人信心65</li>
        <li>个人信心66</li>
        <li>个人信心67</li>
        <li>个人信心68</li>
        <li>个人信心69</li>
        <li>个人信心70</li>
        <li>个人信心71</li>
        <li>个人信心72</li>
        <li>个人信心73</li>
        <li>个人信心74</li>
        <li>个人信心75</li>
        <li>个人信心76</li>
        <li>个人信心77</li>
        <li>个人信心78</li>
        <li>个人信心79</li>
        <li>个人信心80</li>
        <li>个人信心81</li>
        <li>个人信心82</li>
        <li>个人信心83</li>
        <li>个人信心84</li>
        <li>个人信心85</li>
        <li>个人信心86</li>
        <li>个人信心87</li>
        <li>个人信心88</li>
        <li>个人信心89</li>
        <li>个人信心90</li>
        <li>个人信心91</li>
        <li>个人信心92</li>
        <li>个人信心93</li>
        <li>个人信心94</li>
        <li>个人信心95</li>
        <li>个人信心96</li>
        <li>个人信心97</li>
        <li>个人信心98</li>
        <li>个人信心99</li>
        <li>个人信心100</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
  import Scroll from "@/components/common/scroll/Scroll";

  export default {
    name: "Profile",
    components:{
      Scroll
    }
  }
</script>

<style scoped>
  .content{
    height: 300px;
    background-color: #999;
    overflow: hidden;
  }
</style>
